# https://docs.github.com/en/actions

name: "Integrate"

on: # yamllint disable-line rule:truthy
  push:
    branches:
      - "1.x"
  pull_request: null
  schedule:
    - cron: '0 14 * * 1'
  # Allow manually triggering the workflow.
  workflow_dispatch: null

jobs:
  code-coverage:
    name: "Code Coverage"
    uses: "phpDocumentor/.github/.github/workflows/code-coverage.yml@main"
    with:
      composer-root-version: "1.x-dev"

  coding-standards:
    name: "Coding Standards"
    uses: "phpDocumentor/.github/.github/workflows/coding-standards.yml@v0.4.0"
    with:
      composer-root-version: "1.x-dev"

  dependency-analysis:
    name: "Dependency analysis"
    uses: "phpDocumentor/.github/.github/workflows/dependency-analysis.yml@v0.4.0"
    with:
      composer-root-version: "1.x-dev"

  lint-root:
    name: "Lint root"
    uses: "phpDocumentor/.github/.github/workflows/lint.yml@main"
    with:
      composer-options: "--no-check-publish --ansi"

  static-analysis:
    name: "Static analysis"
    uses: "phpDocumentor/.github/.github/workflows/static-analysis.yml@v0.4.0"
    with:
      php-extensions: "none, ctype, dom, json, mbstring, phar, simplexml, tokenizer, xml, xmlwriter, fileinfo, pcntl, posix"
      composer-root-version: "1.x-dev"

  unit-tests:
    name: "Unit test"
    uses: "phpDocumentor/.github/.github/workflows/continuous-integration.yml@v0.5.0"
    with:
      composer-root-version: "1.x-dev"
